[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_src_filter = +<*> -<DisplayModule.cpp> -<EncoderModule.cpp>
lib_deps =
    paulstoffregen/OneWire@2.3.8
    milesburton/DallasTemperature@4.0.6
lib_ignore = LcdUi
